name: 每日触发发送

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: 触发发送
        run: |
          curl "https://79708980.pythonanywhere.com/send_now?token=mytoken123"
